language: python
python:
- '3.5'
install: make install
script: make test
notifications:
  email:
    on_success: never
    on_failure: never
env:
  global:
    - secure: "I98RnlLznknJRQmhRFNRtphjXU7Qt4CQ/Y0Fd4uk2b22PRBXcmzYGwQyBEzC0xZ6ISugVy+xibxJwPUzAX45mePJemmthTpfIh/kqeMPgqz8celXG9iHsXwPVrwB702uiZZ0144kY7vdHJIaFitKQku5gq9SCUcmXrV7YYUn9K4+mzh0TyEMKUiQQmRZuXaXzl+tBPNI5c+jBjEjpNAi2v+OdwVysDSSNJysp5MKqetQrgWwo9CmJI3nEBZo+/7ALTB3Cs+XbiNTzlEa7ZQt6pDOfjg76ArpNIuRcQ8KRvmh5rwoC8Xx2utLm/C+ntselH1Kl9wF3CeLm9Xhjq5aQjaJ48B32bNT6BGyt5x+6APmMSYCfon4BYe1POcMtVG47OvFGoBc7ucaqzQG97dnNmnLSMWHrf2iPfeLHX6eEPk1Imq2ZwRp/rdZH0jOk+DL+OtjLg7mRtqTAovXo7vOlS8IUVvW11vTB0XmBnR1UMdhDu7YHyxNjfTXnub9b2/RlzsF4pKSl9/tbSa+IShYI9hc8ReL6L5SvH0kWSIEG22prxabTwm0ncSfhBgBlNA+hsMOk0p+VohR7N3YEazXELCCjQgURaH+bhCcz5mdAHWgoZOH08ElZNVtcaM8D9XfL2/LbsX2KRhNn9SnKsSyfsxocfGwIB18UnErNbpwIVU="
    - secure: "QnLBgRF0H4tyojW67Sf3uAXdp24S331SYr5NGtUHIhussCMf8yyruKHYFko7t8zRqiFk2UUOthaWwb/LxQaVdD9JeNV46uGYxfePkfdthOSv6L1ZWAlgaa1hwBeWzyZaSwg3K31Iq6GmCPrj/+vvjlkRDh9nFsGEIyV04ADZwlJ51owH2jVekSqCK1IDfAk911hUPbKdo2bCCU0RaUs55bJBsmCJ2yHsOYGadg06AMIpgoG02D7uDjUwNeXC4j0ORYD45NzuSCDoAhoV+QJwm4UOLsx8LF3LxVeN4M/TEmuomfRTet7t1iy0OXl52pRY0eP9f9cVM0NV0ompl0BLplgfZxpcp6IdoZepsW/JeerDsmje5ffQ13CBM7g9hai4Y/s10GNALOxbs7HLpDh4Z5yfI1Rg/BuY1zqTJ4LTg4scyQ7j9G85Nvb7aRefYqrSggkEzkKRpQjUZrJFwNbkYMip8udwa3jpEtxLWw2FsfDu1Zd0Rj3ejP2QQpzUb0oLHCuPsuqGtoimPmN+hOYPCq6PhUHImW3fDrxeCySd9+Do/gAk4tUHpgoXiyWzZj208azEt+gUbHCGt9uf0KJv0Z0naC/qak6zAwwbRNH2wRVliWqSK31AF7AkGx8vhgr33kis0T7Gmt4lCfiavR+lEMjIE328FDpBX6UuUgG6JU8="
