import os

DEBUG = True

TWITTER_CONSUMER_KEY = os.environ['TWITTER_CONSUMER_KEY']
TWITTER_CONSUMER_SECRET = os.environ['TWITTER_CONSUMER_SECRET']
TWITTER_ACCESS_TOKEN = os.environ['TWITTER_ACCESS_TOKEN']
TWITTER_ACCESS_TOKEN_SECRET = os.environ['TWITTER_ACCESS_TOKEN_SECRET']
DEFAULT_TWITTER_USERNAME = 'KevinLyons11'
BAD_TWITTER_USERNAME = 'aye'
TEST = os.environ['TEST']
TWEET_PATH = '/tweets/'
